# Generated by Django 4.2.7 on 2023-11-22 08:12

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0035_auto_20230822_2208"),
        ("test_app", "0006_auto_20200928_0724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpluginmodel",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.CreateModel(
            name="ModelWithPlaceholderField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, default="", max_length=64)),
                (
                    "content1",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        slotname="content1",
                        to="cms.placeholder",
                    ),
                ),
            ],
        ),
    ]
