# Generated by Django 4.2.7 on 2023-11-22 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0007_alter_testpluginmodel_cmsplugin_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelwithplaceholderfield",
            name="content1",
        ),
    ]
